### ISSUE TITLE
github action for docker image needs to not push if build breaks

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#244]

**Comment by ethanwhite** [comment]
Fixed in 6c1cd2e20c304a92bf6682eaecaca9b986e8dc10

**Comment by juniperlsimonis** [comment]
looks like it's actually still broken, but i cannot figure out why it's happening

in the most proximate sense, the break is happening because it's failing on the tests, and it looks like it's getting caught up in the download, but i cannot figure out what the situation is 
i added the timeout override to the github action yaml, but it looks like that didn't fix it either

https://github.com/weecology/portalcasting/pull/247

**Comment by juniperlsimonis** [comment]
fixed https://github.com/weecology/portalcasting/pull/248
